package game

enum class PlanetFeature(
        val description: String,
        val tradeCapacity: Int = 0,
        val explorationMod: Double = 0.0,
        val oreAmt: Int = 0,
        val passiveRepair: Int = 0,
        val discoveryAction: PlanetFeatureAction? = null) {
    NOTHING(                   "Nothing of value."),
    ABANDONED_CITIES(          "Destroyed husks of cities dot the landscape. Metal is easily accessible",
            discoveryAction = ResourceAction(InventoryItem.METAL, 20, 40)),
    PRIMITIVE_LOCALS(          "A low-technology civilization inhabits this planet."), // TODO discovery event
    RICH_RESOURCE_DEPOSITS(    "Rich veins of ore have been detected.",
            oreAmt = 10, discoveryAction = OreAction(30, 60)),
    POOR_RESOURCE_DEPOSITS(    "Sparse veins of ore have been detected.",
            oreAmt = 5, discoveryAction = OreAction(20, 40)),
    UNDERGROUND_CAVERNS(       "Subsurface scan have revealed an extensive cave network beneath the surface, revealing ore deposits.",
            discoveryAction = OreAction(20, 40)),
    CRASHED_SPACESHIP(         "Scattered debris surrounds the wreck of a starship on the surface.",
            discoveryAction = ResourceAction(InventoryItem.METAL, 10, 20)),
    SMALL_COLONY(              "A small but prosperous alien colony is present on this planet.",
            tradeCapacity = 1500),
    LARGE_COLONY(              "A large alien colony is present on this planet, and is open to trade.",
            tradeCapacity = 4000),
    HEAVILY_SETTLED(           "This is home to a massive civilzation that spans the planet.",
            tradeCapacity = 10000, explorationMod = 1.0),
    CARNIVOROUS_PLANTS(        "The flora on this planet has acquired a taste for meat! Exploration will be more difficult.",
            explorationMod = -0.1),
    MASSIVE_CANYON(            "An enormous canyon stretches across the landscape, exposing ore veins.",
            discoveryAction = OreAction(10, 20)),
    RARE_ELEMENTS(             "Traces of rare and valuable elements have been detected.",
            discoveryAction = ResourceAction(InventoryItem.RARE_METALS, 10, 20)),
    COLONIZED_MOON(            "One of this planet's moons is home to a small outpost.",
            tradeCapacity = 750),
    UNUSUAL_GASES(             "This planet's atmosphere contains a peculiar mix of gases, from which rare elements can be extracted.",
            discoveryAction = ResourceAction(InventoryItem.RARE_METALS, 5, 10)),
    MASSIVE_SHIPYARDS(         "A massive ship-building complex is present in orbit.",
            passiveRepair = 5),
    WRECKED_SHIPYARDS(         "The shattered remains of what was once a massive ship-building-complex is present in orbit.",
            discoveryAction = CompoundAction(ResourceAction(InventoryItem.METAL, 30, 60), ResourceAction(InventoryItem.TECHNOLOGY, 5, 10))),
    RING_SYSTEM("This planet is host to a set of beautiful rings of ice and rock, rich in rare elements.",
            discoveryAction = ResourceAction(InventoryItem.RARE_METALS, 5, 10)),
    JUPITER_BRAIN("There seems to be a massive intelligence lurking within this planet..."), // TODO requires mysterious signal
    FEROCIOUS_FAUNA("The wildlife on this planet is especially aggressive and dangerous.",
            explorationMod = -0.1),
    ANCIENT_SHIP("The ancient hulk of an alien starship lurks above this planet.",
            discoveryAction = CompoundAction(ResourceAction(InventoryItem.METAL, 10, 20), ResourceAction(InventoryItem.TECHNOLOGY, 5, 10))),
    DESTROYED_SHIP("A field of debris surrounds the remains of a destroyed cruiser in orbit of this planet.",
            discoveryAction = ResourceAction(InventoryItem.METAL, 10, 20)),
    ABANDONDED_SHIP("A large passenger ship lies abandoned in orbit of this planet.",
            discoveryAction = CompoundAction(ResourceAction(InventoryItem.METAL, 10, 20), ResourceAction(InventoryItem.GOODS, 10, 20))),
    ELECTROMAGNETIC_DISTORTIONS("Sensors are being distorted by some phenomenon around this planet.",
            explorationMod = -0.1),
    REFUGEES_ON_SURFACE("A small band of refugees is present on the surface. They may not last much longer."), // TODO
    REFUGEES_IN_ORBIT("A small ship is drifting in orbit, its engines disabled. There are life-signs aboard."), // TODO
    COLONY_DISTRESS_SIGNAL("A wavering distress signal is being emitted from the planet's surface.") // TODO
}
