package game

enum class PlanetFeature {
    NOTHING,
    ABANDONED_CITIES,
    PRIMITIVE_LOCALS,
    RICH_RESOURCE_DEPOSITS,
    POOR_RESOURCE_DEPOSITS,
    UNDERGROUND_CAVERNS,
    CRASHED_SPACESHIP,
    SMALL_COLONY,
    LARGE_COLONY,
    HEAVILY_SETTLED,
    CARNIVOROUS_PLANTS,
    MASSIVE_CANYON,
    RARE_ELEMENTS,
    COLONIZED_MOON,
    NUCLEAR_WINTER,
    UNUSUAL_GASES,
    MASSIVE_SHIPYARDS,
    RING_SYSTEM,
    JUPITER_BRAIN,
    FEROCIOUS_FAUNA,
    DERELICT_SHIP,
    ELECTROMAGNETIC_DISTORTIONS
}
